apiVersion: apps/v1
kind: Deployment
metadata:
  name: harnesslab
  labels:
    app: jhttp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhttp
  spec:
    containers:
      - name: harnesslab
        image: hootienofish/harnesslab:latest
    imagePullSecrets:
      - name: regcred
