pipeline:
  name: selab
  identifier: selab
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: SELab
        repoName: jhttp
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: SELabK8S
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: SELabConnector
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: build java app
                  identifier: build_java_app
                  spec:
                    connectorRef: SELabConnector
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
                  description: Build Java App
              - step:
                  type: Run
                  name: check dependencies
                  identifier: check_dependencies
                  spec:
                    connectorRef: SELabConnector
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: mvn dependency-check:check -U -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/target/*.xml
              - step:
                  type: Test
                  name: RunTestsWithIntelligence
                  identifier: RunTestsWithIntelligence
                  spec:
                    connectorRef: SELabConnector
                    image: maven:3.8-jdk-11
                    shell: Sh
                    command: |-
                      mvn test
                      mvn package -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
                    intelligenceMode: true
